export const initialCategories = [
  {
    id: 1,
    name: 'Web Development',
    slug: 'web-development',
    description: 'Master modern frontend, backend, and full-stack engineering with cutting-edge industry frameworks.',
    image: '/images/web_dev.jpg',
    courseCount: 6,
  },
  {
    id: 2,
    name: 'Cloud Computing & DevOps',
    slug: 'cloud-computing',
    description: 'Learn AWS, Docker, Kubernetes, CI/CD pipelines, and enterprise infrastructure automation.',
    image: '/images/cloud_devops.jpg',
    courseCount: 4,
  },
  {
    id: 3,
    name: 'Artificial Intelligence & Data',
    slug: 'artificial-intelligence',
    description: 'Build predictive AI models, neural networks, LLM agents, and data science pipelines.',
    image: '/images/ai_ml.jpg',
    courseCount: 5,
  },
  {
    id: 4,
    name: 'Cybersecurity & Defense',
    slug: 'cybersecurity',
    description: 'Hands-on network security, penetration testing, threat hunting, and ethical hacking.',
    image: '/images/cyber_security.jpg',
    courseCount: 3,
  },
  {
    id: 5,
    name: 'UI/UX Design & Product',
    slug: 'ui-ux-design',
    description: 'Design intuitive, accessible, and delightful digital user interfaces using Figma and design systems.',
    image: '/images/ui_ux.jpg',
    courseCount: 4,
  },
];

export const initialLecturers = [
  {
    id: 1,
    name: 'Prof. Sarah Jenkins',
    designation: 'Principal Software Architect & Full-Stack Lead',
    profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    bio: 'Former Tech Lead at Stripe and senior educator with over a decade of experience scaling enterprise distributed systems.',
    qualification: 'Ph.D. in Computer Science, Stanford University',
    experience_years: 12,
    specialization: 'Full-Stack Architecture, React, Node.js & Distributed Systems',
    email: 'sarah.jenkins@coursegallery.edu',
    linkedin: 'https://linkedin.com/in/sarah-jenkins-educator',
    active_status: true,
  },
  {
    id: 2,
    name: 'Dr. Aris Thorne',
    designation: 'Director of AI Research & Senior Data Scientist',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    bio: 'Pioneering researcher in transformer models, generative AI, and predictive analytics with 20+ published academic papers.',
    qualification: 'Ph.D. in Machine Learning, MIT',
    experience_years: 14,
    specialization: 'Generative AI, Deep Learning, PyTorch & LLM Fine-tuning',
    email: 'aris.thorne@coursegallery.edu',
    linkedin: 'https://linkedin.com/in/aris-thorne-ai',
    active_status: true,
  },
  {
    id: 3,
    name: 'David Chen',
    designation: 'AWS Certified Solutions Architect & SRE Lead',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    bio: 'Specialist in high-availability multi-region cloud architectures, Kubernetes orchestration, and zero-downtime CI/CD.',
    qualification: 'M.Sc. in Cloud Computing, UC Berkeley',
    experience_years: 9,
    specialization: 'Cloud Infrastructure, Kubernetes, Terraform & Site Reliability',
    email: 'david.chen@coursegallery.edu',
    linkedin: 'https://linkedin.com/in/david-chen-cloud',
    active_status: true,
  },
  {
    id: 4,
    name: 'Elena Rostova',
    designation: 'Chief Information Security Officer & Ethical Hacker',
    profile_image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    bio: 'Certified ethical hacker (OSCP, CISSP) advising Fortune 500 companies on cyber defense strategies and penetration testing.',
    qualification: 'M.Sc. in Cybersecurity, Oxford University',
    experience_years: 11,
    specialization: 'Penetration Testing, Cryptography, Zero-Trust Architecture',
    email: 'elena.rostova@coursegallery.edu',
    linkedin: 'https://linkedin.com/in/elena-rostova-sec',
    active_status: true,
  },
];

export const initialCourses = [
  {
    id: 1,
    course_title: 'Full-Stack Web Development with React & Node.js',
    slug: 'full-stack-web-development-react-node',
    course_code: 'FSW-101',
    short_description: 'Master modern full-stack web engineering from frontend components to scalable REST APIs and relational databases.',
    full_description: 'This comprehensive bootcamp immerses you in modern web engineering. You will master React 19, Tailwind CSS, Node.js, Express, and database management, building real-world production systems with authentication and real-time state.',
    course_thumbnail: '/images/web_dev.jpg',
    course_banner: '/images/web_dev.jpg',
    category: {
      id: 1,
      name: 'Web Development',
      slug: 'web-development',
    },
    lecturer: {
      id: 1,
      name: 'Prof. Sarah Jenkins',
      designation: 'Principal Software Architect',
      profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    },
    price: 350.0,
    discount_price: 249.0,
    currency: 'USD',
    duration: '6 Months',
    lesson_count: 48,
    course_level: 'Intermediate',
    delivery_mode: 'Online',
    start_date: '2026-10-01',
    end_date: '2027-04-01',
    requirements: 'Basic familiarity with HTML, CSS, and introductory JavaScript fundamentals.',
    what_you_learn: '• Build interactive SPAs with React\n• Architect scalable backend APIs with Express\n• Manage relational databases with MySQL & Knex\n• Deploy to containerized production cloud environments\n• Implement HTTP-only cookie authentication & OAuth',
    certification: true,
    featured_course: true,
    status: 'Published',
    seo_title: 'Full-Stack Web Development Bootcamp - React & Node.js',
    seo_description: 'Become a certified full-stack web developer with hands-on projects, expert mentorship, and industry best practices.',
  },
  {
    id: 2,
    course_title: 'AI & Machine Learning Engineering Masterclass',
    slug: 'ai-machine-learning-engineering-masterclass',
    course_code: 'AIML-201',
    short_description: 'Delve into neural networks, PyTorch, computer vision, and building autonomous LLM agents.',
    full_description: 'Step into the cutting-edge realm of artificial intelligence. Master machine learning mathematics, deep neural networks, transformer architectures, and deploy intelligent agents capable of complex decision making.',
    course_thumbnail: '/images/ai_ml.jpg',
    course_banner: '/images/ai_ml.jpg',
    category: {
      id: 3,
      name: 'Artificial Intelligence & Data',
      slug: 'artificial-intelligence',
    },
    lecturer: {
      id: 2,
      name: 'Dr. Aris Thorne',
      designation: 'Director of AI Research',
      profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    },
    price: 450.0,
    discount_price: 320.0,
    currency: 'USD',
    duration: '8 Months',
    lesson_count: 64,
    course_level: 'Advanced',
    delivery_mode: 'Hybrid',
    start_date: '2026-10-15',
    end_date: '2027-06-15',
    requirements: 'Solid understanding of Python programming and introductory linear algebra & calculus.',
    what_you_learn: '• Train deep neural networks with PyTorch\n• Fine-tune large language models and RAG architectures\n• Implement computer vision and NLP models\n• Deploy AI models to edge and cloud inference endpoints',
    certification: true,
    featured_course: true,
    status: 'Published',
    seo_title: 'AI & Machine Learning Masterclass | Course Gallery',
    seo_description: 'Gain elite AI engineering skills under the guidance of top researchers. PyTorch, LLMs, and neural architectures.',
  },
  {
    id: 3,
    course_title: 'AWS Cloud Architecture & Kubernetes DevOps Bootcamp',
    slug: 'aws-cloud-architecture-kubernetes-bootcamp',
    course_code: 'CLD-301',
    short_description: 'Design enterprise cloud infrastructure, automate CI/CD, and orchestrate containers with Kubernetes.',
    full_description: 'Prepare for AWS Solutions Architect & CKA certifications. You will build high-availability VPC networks, manage Kubernetes clusters, automate with Terraform, and implement proactive observability.',
    course_thumbnail: '/images/cloud_devops.jpg',
    course_banner: '/images/cloud_devops.jpg',
    category: {
      id: 2,
      name: 'Cloud Computing & DevOps',
      slug: 'cloud-computing',
    },
    lecturer: {
      id: 3,
      name: 'David Chen',
      designation: 'AWS Certified Solutions Architect',
      profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    },
    price: 390.0,
    discount_price: 279.0,
    currency: 'USD',
    duration: '5 Months',
    lesson_count: 42,
    course_level: 'Intermediate',
    delivery_mode: 'Online',
    start_date: '2026-11-01',
    end_date: '2027-04-01',
    requirements: 'Basic Linux shell command line skills and fundamental networking knowledge.',
    what_you_learn: '• Architect fault-tolerant AWS cloud topologies\n• Containerize services with Docker & Kubernetes\n• Write Infrastructure as Code with Terraform\n• Implement Prometheus & Grafana monitoring dashboards',
    certification: true,
    featured_course: true,
    status: 'Published',
    seo_title: 'AWS Cloud Architecture & Kubernetes Bootcamp',
    seo_description: 'Become a certified DevOps engineer with hands-on AWS, Docker, Kubernetes, and Terraform labs.',
  },
  {
    id: 4,
    course_title: 'Ethical Hacking & Defensive Cybersecurity',
    slug: 'ethical-hacking-defensive-cybersecurity',
    course_code: 'SEC-401',
    short_description: 'Practical penetration testing, defensive hardening, vulnerability analysis, and incident response.',
    full_description: 'Learn offensive techniques to build bulletproof defense. Conduct vulnerability scanning, exploit analysis, web application penetration testing, and configure zero-trust network defenses.',
    course_thumbnail: '/images/cyber_security.jpg',
    course_banner: '/images/cyber_security.jpg',
    category: {
      id: 4,
      name: 'Cybersecurity & Defense',
      slug: 'cybersecurity',
    },
    lecturer: {
      id: 4,
      name: 'Elena Rostova',
      designation: 'Chief Information Security Officer',
      profile_image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    },
    price: 420.0,
    discount_price: 299.0,
    currency: 'USD',
    duration: '6 Months',
    lesson_count: 50,
    course_level: 'Advanced',
    delivery_mode: 'Physical',
    start_date: '2026-10-20',
    end_date: '2027-04-20',
    requirements: 'Strong TCP/IP networking foundation and familiarity with Linux security concepts.',
    what_you_learn: '• Penetration testing methodology & Kali Linux tools\n• OWASP Top 10 vulnerabilities and exploitation\n• Cryptography, SSL/TLS, and secure communication\n• Incident response, digital forensics, and SOC operations',
    certification: true,
    featured_course: true,
    status: 'Published',
    seo_title: 'Ethical Hacking & Defensive Cybersecurity Masterclass',
    seo_description: 'Learn hands-on ethical hacking, penetration testing, and enterprise defensive security.',
  },
  {
    id: 5,
    course_title: 'Next.js 15 & Modern Frontend Engineering',
    slug: 'nextjs-modern-frontend-engineering',
    course_code: 'NXT-202',
    short_description: 'Build hyper-fast Server Components, dynamic streaming apps, and edge-rendered web platforms.',
    full_description: 'Explore the modern capabilities of Next.js 15 App Router. Learn Server Actions, partial prerendering, parallel routes, and state-of-the-art caching mechanisms for lightning-fast user experiences.',
    course_thumbnail: '/images/web_dev.jpg',
    course_banner: '/images/web_dev.jpg',
    category: {
      id: 1,
      name: 'Web Development',
      slug: 'web-development',
    },
    lecturer: {
      id: 1,
      name: 'Prof. Sarah Jenkins',
      designation: 'Principal Software Architect',
      profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    },
    price: 280.0,
    discount_price: 199.0,
    currency: 'USD',
    duration: '4 Months',
    lesson_count: 36,
    course_level: 'Beginner',
    delivery_mode: 'Online',
    start_date: '2026-11-15',
    end_date: '2027-03-15',
    requirements: 'Basic JavaScript and React fundamentals.',
    what_you_learn: '• App Router, React Server Components & Streaming\n• Next.js Server Actions and mutation patterns\n• Edge middleware and multi-tenant authentication\n• Performance profiling and Core Web Vitals optimization',
    certification: true,
    featured_course: false,
    status: 'Published',
    seo_title: 'Next.js 15 App Router & Server Components Bootcamp',
    seo_description: 'Master React Server Components, streaming SSR, and edge deployment with Next.js 15.',
  },
  {
    id: 6,
    course_title: 'UI/UX Design Systems & Product Strategy',
    slug: 'ui-ux-design-systems-product-strategy',
    course_code: 'DSN-105',
    short_description: 'Create cohesive design systems in Figma, conduct user research, and build interactive prototypes.',
    full_description: 'Bridge the gap between design and development. Learn atomic design theory, design tokens, responsive layouts, usability testing, and handoff workflows that delight engineering teams.',
    course_thumbnail: '/images/ui_ux.jpg',
    course_banner: '/images/ui_ux.jpg',
    category: {
      id: 5,
      name: 'UI/UX Design & Product',
      slug: 'ui-ux-design',
    },
    lecturer: {
      id: 1,
      name: 'Prof. Sarah Jenkins',
      designation: 'Principal Software Architect',
      profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    },
    price: 260.0,
    discount_price: 185.0,
    currency: 'USD',
    duration: '3 Months',
    lesson_count: 28,
    course_level: 'Beginner',
    delivery_mode: 'Physical',
    start_date: '2026-10-05',
    end_date: '2027-01-05',
    requirements: 'No prior design experience required. Curiosity and creative enthusiasm.',
    what_you_learn: '• Figma masterclass: auto-layout, variables & interactive components\n• Atomic design systems and enterprise token architecture\n• User testing protocols and wireframing\n• Accessibility compliance (WCAG 2.2)',
    certification: true,
    featured_course: false,
    status: 'Published',
    seo_title: 'UI/UX Design Systems & Product Strategy Masterclass',
    seo_description: 'Design beautiful, production-ready design systems and user experiences in Figma.',
  },
];
