import React, { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, CircleDollarSign, Library, LogOut, Search } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:1337/api';

async function request(path, options = {}) {
  const token = import.meta.env.VITE_API_TOKEN;
  const response = await fetch(`${API_URL}${path}`, {
    ...options,
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers },
  });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body?.error?.message || 'Request failed');
  return body;
}

function Auth({ register, onSuccess }) {
  const [form, setForm] = useState({ identifier: '', username: '', email: '', password: '', firstName: '', lastName: '', phone: '', address: '', gender: 'Female' });
  const [error, setError] = useState('');
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  async function submit(event) {
    event.preventDefault(); setError('');
    try {
      const data = register
        ? { username: form.username, email: form.email, password: form.password, firstName: form.firstName, lastName: form.lastName, phone: Number(form.phone), address: form.address, gender: form.gender }
        : { identifier: form.identifier, password: form.password };
      onSuccess(register ? await request('/auth/local/register', { method: 'POST', body: JSON.stringify(data) }) : await request('/auth/local', { method: 'POST', body: JSON.stringify(data) }));
    } catch (err) { setError(err.message); }
  }
  return <main className="auth-page"><section className="auth-visual"><div className="visual-mark"><BookOpen size={20} /> LEAF & LEDGER</div><div className="visual-copy"><p className="eyebrow">A quieter way to read</p><h1>Keep your next chapter close.</h1><p>Organize a living collection, borrow with confidence, and make room for stories worth returning to.</p></div></section><section className="auth-panel"><div className="auth-form-wrap"><p className="eyebrow">{register ? 'Join the library' : 'Welcome back'}</p><h2>{register ? 'Start your shelf.' : 'Open your shelf.'}</h2><p className="muted">Your personal home for the books you want to remember.</p><form className="stack-form" onSubmit={submit}>{register ? <><div className="field-row"><label>First name<input required value={form.firstName} onChange={update('firstName')} /></label><label>Last name<input required value={form.lastName} onChange={update('lastName')} /></label></div><label>Username<input required value={form.username} onChange={update('username')} /></label><label>Email<input required type="email" value={form.email} onChange={update('email')} /></label><div className="field-row"><label>Phone<input required type="number" value={form.phone} onChange={update('phone')} /></label><label>Gender<select value={form.gender} onChange={update('gender')}><option>Female</option><option>Male</option></select></label></div><label>Address<input required value={form.address} onChange={update('address')} /></label></> : <label>Email or username<input required value={form.identifier} onChange={update('identifier')} /> </label>}<label>Password<input required type="password" minLength="6" value={form.password} onChange={update('password')} /></label>{error && <p className="error-text">{error}</p>}<button className="button primary full">{register ? 'Create my account' : 'Enter the library'} <ArrowRight size={17} /></button></form><p className="switch-auth"><a href={register ? '/login' : '/register'}>{register ? 'Already have an account? Sign in' : 'New to Leaf & Ledger? Create an account'}</a></p></div></section></main>;
}

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('leaf_user') || 'null'));
  const [page, setPage] = useState(window.location.pathname === '/books' ? 'books' : window.location.pathname === '/loans' ? 'loans' : window.location.pathname === '/fines' ? 'fines' : 'dashboard');
  const register = window.location.pathname === '/register';
  if (!user) return <Auth register={register} onSuccess={(result) => { localStorage.setItem('leaf_user', JSON.stringify(result.user)); setUser(result.user); window.history.pushState({}, '', '/'); }} />;
  const logout = () => { localStorage.removeItem('leaf_user'); setUser(null); window.history.pushState({}, '', '/login'); };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><BookOpen size={19} /></span><span>Leaf & Ledger</span></div><p className="nav-label">Workspace</p><nav>{[['dashboard', 'Overview', <Library size={18} />], ['books', 'Book catalog', <BookOpen size={18} />], ['loans', 'My loans', <CalendarDays size={18} />], ['fines', 'Fines', <CircleDollarSign size={18} />]].map(([key, label, icon]) => <button className={page === key ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(key); window.history.pushState({}, '', key === 'dashboard' ? '/' : `/${key}`); }} key={key}>{icon}<span>{label}</span></button>)}</nav><button className="logout" onClick={logout}><LogOut size={17} /> Sign out</button></aside><div className="main-area"><header className="topbar"><div className="crumb">Library / <strong>{user.firstName || user.username}</strong></div></header><main className="content">{page === 'dashboard' && <Dashboard />}{page === 'books' && <Books />}{page === 'loans' && <Loans />}{page === 'fines' && <Fines />}</main></div></div>;
}

function Dashboard() { const [stats, setStats] = useState(null); useEffect(() => { Promise.all([request('/books?pagination[pageSize]=100'), request('/borrow-records?pagination[pageSize]=100'), request('/fines?pagination[pageSize]=100')]).then(([books, loans, fines]) => { const bookCount = books.meta?.pagination?.total ?? books.data?.length ?? 0; const loanItems = loans.data || []; const activeLoans = loanItems.filter((loan) => ['Borrowed', 'Late'].includes(loan.lend_status)).length; const fineItems = fines.data || []; setStats({ totalBooks: bookCount, availableBooks: Math.max(0, bookCount - activeLoans), borrowedBooks: activeLoans, pendingFines: fineItems.filter((fine) => !fine.paid).length }); }).catch(() => {}); }, []); return <><PageHeading title="Good morning, reader." description="A clear view of your collection and everything currently in motion." /><div className="stat-grid">{[['Total books', stats?.totalBooks], ['Available now', stats?.availableBooks], ['On loan', stats?.borrowedBooks], ['Pending fines', stats?.pendingFines]].map(([label, value]) => <div className="stat-card" key={label}><div><span>{label}</span><strong>{value ?? '—'}</strong></div></div>)}</div><section className="feature-panel"><div className="feature-image"><img src="https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1000&q=80" alt="Warm library shelves" /></div><div className="feature-copy"><span className="eyebrow">Reading room</span><h3>Make space for a story that stays.</h3><p>Browse the collection and find a new favorite.</p></div></section></>; }
function Books() { const [books, setBooks] = useState([]); const [search, setSearch] = useState(''); useEffect(() => { const query = search ? `&filters[$or][0][title][$containsi]=${encodeURIComponent(search)}&filters[$or][1][isbn][$containsi]=${encodeURIComponent(search)}` : ''; request(`/books?populate=*&sort=title:asc${query}`).then((result) => setBooks(result.data || [])).catch(() => setBooks([])); }, [search]); return <><PageHeading title="Book catalog" description="Find your next story across the library collection." /><div className="toolbar"><div className="search-box"><Search size={18} /><input placeholder="Search by title or ISBN" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div><div className="book-grid">{books.map((book) => <article className="book-card" key={book.id || book.documentId}><div className="book-cover"><div className="cover-placeholder"><BookOpen size={30} /><span>{book.title?.[0]}</span></div></div><div className="book-info"><span className="book-category">{book.category?.name || 'Reading list'}</span><h3>{book.title}</h3><p>{book.author?.name || 'Unknown author'}</p></div></article>)}</div>{!books.length && <Empty text="No books found." />}</>; }
function Loans() { const [loans, setLoans] = useState([]); const user = JSON.parse(localStorage.getItem('leaf_user') || 'null'); useEffect(() => { const userFilter = user?.id ? `&filters[users_permissions_user][id][$eq]=${user.id}` : ''; request(`/borrow-records?populate=*&sort=borrow_date:desc${userFilter}`).then((result) => setLoans(result.data || [])).catch(() => {}); }, [user?.id]); return <><PageHeading title="My loans" description="Keep an eye on active reads and returned stories." /><section className="panel table-panel">{loans.map((loan) => <div className="table-row" key={loan.id || loan.documentId}><strong>{loan.book?.title || 'Book'}</strong><span>{loan.lend_status}</span><span>{new Date(loan.due_date).toLocaleDateString()}</span></div>)}{!loans.length && <Empty text="No loans yet." />}</section></>; }
function Fines() { const [fines, setFines] = useState([]); const user = JSON.parse(localStorage.getItem('leaf_user') || 'null'); useEffect(() => { const userFilter = user?.id ? `&filters[users_permissions_user][id][$eq]=${user.id}` : ''; request(`/fines?populate=*&sort=createdAt:desc${userFilter}`).then((result) => setFines(result.data || [])).catch(() => {}); }, [user?.id]); return <><PageHeading title="Fines" description="Review your account standing." /><section className="panel table-panel">{fines.map((fine) => <div className="table-row" key={fine.id}><strong>{fine.reason}</strong><span>${Number(fine.amount).toFixed(2)}</span><span>{fine.paid ? 'Paid' : 'Pending'}</span></div>)}{!fines.length && <Empty text="You have a clean account." />}</section></>; }
function PageHeading({ title, description }) { return <div className="page-heading"><div><p className="eyebrow">Leaf & Ledger</p><h1>{title}</h1><p className="muted">{description}</p></div></div>; }
function Empty({ text }) { return <div className="empty-state"><BookOpen size={25} /><p>{text}</p></div>; }

export default App;